# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PBO2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 507)
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(250, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("  width: 100%;\n"
"  padding: 5px;\n"
"  border: 2px solid #ddd;\n"
"  border-radius: 5px;\n"
"  background-color: #f9f9f9;\n"
"  appearance: none; \n"
"  cursor: pointer;\n"
"  transition: all 0.3s ease;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 150, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("  width: 100%;\n"
"  border-radius: 5px;\n"
"  border: none;\n"
"  box-shadow: 2px 2px black;\n"
"  transition: all 0.3s ease;\n"
"  cursor: pointer;\n"
"  background-color: #7bed9f;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 180, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("  width: 100%;\n"
"  border-radius: 5px;\n"
"  border: none;\n"
"  box-shadow: 2px 2px black;\n"
"  transition: all 0.3s ease;\n"
"  cursor: pointer;\n"
"  background-color: red;\n"
"  color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 280, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 120, 111, 20))
        self.lineEdit_5.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("padding: 5px;")
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 150, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("  width: 100%;\n"
"  border-radius: 5px;\n"
"  border: none;\n"
"  box-shadow: 2px 2px black;\n"
"  transition: all 0.3s ease;\n"
"  cursor: pointer;\n"
"  background-color: #eccc68;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 180, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("  width: 100%;\n"
"  border-radius: 5px;\n"
"  border: none;\n"
"  transition: all 0.3s ease;\n"
"  cursor: pointer;\n"
"  background-color: #1e90ff;\n"
"  color: white;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 310, 311, 121))
        self.listWidget.setStyleSheet("background-color: white;")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 390, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 90, 111, 20))
        self.lineEdit_6.setStyleSheet("border-radius: 3px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 90, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("padding: 5px;")
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 220, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("padding: 5px;\n"
"background-color: transparent;")
        self.radioButton.setObjectName("radioButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("padding: 5px;\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 220, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Afacad Flux")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("padding: 5px;\n"
"background-color: transparent;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 210, 141, 41))
        self.frame.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(182, 182, 182);\n"
"padding: 5px;\n"
"background-color: white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_5.raise_()
        self.label_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.listWidget.raise_()
        self.pushButton_7.raise_()
        self.lineEdit_6.raise_()
        self.label_3.raise_()
        self.radioButton.raise_()
        self.label_4.raise_()
        self.radioButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nama"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Alamat"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Nomor HP"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Jaminan"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Carrier"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Tas"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Tenda"))
        self.pushButton.setText(_translate("MainWindow", "Tambah"))
        self.pushButton_2.setText(_translate("MainWindow", "Hapus"))
        self.label.setText(_translate("MainWindow", "List Sewaan"))
        self.pushButton_3.setText(_translate("MainWindow", "Cetak QR"))
        self.pushButton_4.setText(_translate("MainWindow", "Konfirmasi"))
        self.label_2.setText(_translate("MainWindow", "Jumlah"))
        self.pushButton_5.setText(_translate("MainWindow", "Edit"))
        self.pushButton_6.setText(_translate("MainWindow", "Detail"))
        self.pushButton_7.setText(_translate("MainWindow", "iReport"))
        self.label_3.setText(_translate("MainWindow", "Harga"))
        self.radioButton.setText(_translate("MainWindow", "Laki"))
        self.label_4.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.radioButton_2.setText(_translate("MainWindow", "Perempuan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
