# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biodata.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 517)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setAutoFillBackground(False)
        self.nama = QtWidgets.QLabel(Form)
        self.nama.setGeometry(QtCore.QRect(10, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nama.setFont(font)
        self.nama.setStyleSheet("#nama{\n"
"\n"
"\n"
"background-color : purple;\n"
"color:white;\n"
"}")
        self.nama.setObjectName("nama")
        self.alamat = QtWidgets.QLabel(Form)
        self.alamat.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alamat.setFont(font)
        self.alamat.setStyleSheet("#alamat{\n"
"\n"
"background-color : purple;\n"
"color:white;\n"
"\n"
"}")
        self.alamat.setObjectName("alamat")
        self.isinama = QtWidgets.QLineEdit(Form)
        self.isinama.setGeometry(QtCore.QRect(120, 10, 491, 51))
        self.isinama.setStyleSheet("#isinama{\n"
"\n"
"background-color: pink;\n"
"color: white;\n"
"\n"
"\n"
"}")
        self.isinama.setObjectName("isinama")
        self.isialamat = QtWidgets.QLineEdit(Form)
        self.isialamat.setGeometry(QtCore.QRect(120, 80, 491, 51))
        self.isialamat.setStyleSheet("#isialamat{\n"
"\n"
"background-color:pink;\n"
"color:white;\n"
"\n"
"}")
        self.isialamat.setObjectName("isialamat")
        self.tambah = QtWidgets.QPushButton(Form)
        self.tambah.setGeometry(QtCore.QRect(220, 260, 171, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tambah.sizePolicy().hasHeightForWidth())
        self.tambah.setSizePolicy(sizePolicy)
        self.tambah.setMinimumSize(QtCore.QSize(5, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.tambah.setFont(font)
        self.tambah.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tambah.setStyleSheet("#tambah {\n"
"\n"
"background-color: purple;\n"
"color:white;\n"
"\n"
"}")
        self.tambah.setObjectName("tambah")
        self.edit = QtWidgets.QPushButton(Form)
        self.edit.setGeometry(QtCore.QRect(220, 320, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit.setFont(font)
        self.edit.setStyleSheet("#edit{\n"
"\n"
"background-color:purple;\n"
"color:white;\n"
"\n"
"\n"
"}")
        self.edit.setObjectName("edit")
        self.hapus = QtWidgets.QPushButton(Form)
        self.hapus.setGeometry(QtCore.QRect(220, 380, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setStyleSheet("#hapus{\n"
"\n"
"background-color:purple;\n"
"color:white;\n"
"\n"
"\n"
"}")
        self.hapus.setObjectName("hapus")
        self.cari = QtWidgets.QPushButton(Form)
        self.cari.setGeometry(QtCore.QRect(220, 440, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cari.setFont(font)
        self.cari.setStyleSheet("#cari{\n"
"\n"
"background-color:purple;\n"
"color:white;\n"
"\n"
"\n"
"}")
        self.cari.setObjectName("cari")
        self.pembatas = QtWidgets.QFrame(Form)
        self.pembatas.setGeometry(QtCore.QRect(-1, 350, 631, 31))
        self.pembatas.setStyleSheet("#pembatas{\n"
"\n"
"background-color:pink;\n"
"\n"
"\n"
"\n"
"}")
        self.pembatas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pembatas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pembatas.setObjectName("pembatas")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nama.setText(_translate("Form", "NAMA : "))
        self.alamat.setText(_translate("Form", "ALAMAT :"))
        self.tambah.setText(_translate("Form", "TAMBAH DATA"))
        self.edit.setText(_translate("Form", "EDIT DATA"))
        self.hapus.setText(_translate("Form", "HAPUS DATA"))
        self.cari.setText(_translate("Form", "CARI DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
